In [99]:
from tqdm.autonotebook import tqdm
import pandas as pd
import numpy as np
from pathlib import Path
import faiss

In [100]:
res = faiss.StandardGpuResources()  # use a single GPU

In [88]:
from pathlib import Path
# embeddings_folder = Path("/opt/home/cleong/data/semlex_asl_citizen_popsign_combined_mini")
embeddings_folder = Path("/opt/home/cleong/data/ASL_Citizen/embeddings")
semlex_model_embeddings = list(embeddings_folder.rglob("*sem-lex*.npy"))

In [101]:
len(semlex_model_embeddings)

83112

In [90]:
def load_pose_embedding(embedding_path):
    embeddings = np.load(embedding_path).squeeze()
    # print(f"loaded embeddings with shape {embeddings.shape}")  # (1, 768)
    #   print(f"{embeddings[0]}=") # big long bunch of numbers
    # print(f"loaded embeddings with shape {embeddings}")
    return embeddings

In [80]:
# def list_of_paths_to_np_array(paths):
#     return np.array([load_pose_embedding(p) for p in tqdm(paths, desc="loading paths")])

In [108]:
def paths_to_dataframe(paths):
    data = [
        {
            "video_id": p.name.split("-")[0],
            "file_path": p,
            "file_name": Path(p).name,
            "embedding": load_pose_embedding(p),
        
        }
        for p in tqdm(paths, desc="loading paths")
    ]
    return pd.DataFrame(data)

In [109]:
split_index = 20
reference_paths = semlex_model_embeddings[split_index:]
query_paths = semlex_model_embeddings[:split_index]

In [110]:
query_df = paths_to_dataframe(query_paths)
query_df

loading paths: 100%|██████████| 20/20 [00:00<00:00, 4380.93it/s]

,video_id,file_path,file_name,embedding
0,4512868342911205,/opt/home/cleong/data/ASL_Citizen/embeddings/4...,4512868342911205-RESPONSIBILITY-using-model-se...,"[-0.33322427, 0.16524771, 0.11535681, 0.368136..."
1,802432162454322,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,802432162454322-VITAMINS-using-model-sem-lex.npy,"[-0.23754077, 0.3569193, -0.3196658, 0.1353952..."
2,29766213567797584,/opt/home/cleong/data/ASL_Citizen/embeddings/2...,29766213567797584-ENVELOPE-using-model-sem-lex...,"[0.18618162, 0.1113351, -0.072578825, -0.10251..."
3,1989909351732737,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,1989909351732737-FUNCTION-using-model-sem-lex.npy,"[-0.024617223, -0.20148936, -0.0022485945, 0.2..."
4,7075908041208987,/opt/home/cleong/data/ASL_Citizen/embeddings/7...,7075908041208987-STORY_3-using-model-sem-lex.npy,"[-0.3644051, 0.06412346, 0.020423084, 0.035708..."
5,08540962663657381,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,08540962663657381-TIE-using-model-sem-lex.npy,"[0.07949132, -0.15333198, 0.06991726, 0.131780..."
6,029833014387566248,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,029833014387566248-SAIL_2-using-model-sem-lex.npy,"[-0.20589952, -0.4929245, -0.405769, 0.4774660..."
7,8555548615892776,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,8555548615892776-HOE-using-model-sem-lex.npy,"[-0.042334426, -1.0742257, -0.4117589, 0.04502..."
8,2753221560775323,/opt/home/cleong/data/ASL_Citizen/embeddings/2...,2753221560775323-RACE-using-model-sem-lex.npy,"[0.15693352, -0.44518018, -0.010830048, 0.2055..."
9,484005199725384,/opt/home/cleong/data/ASL_Citizen/embeddings/4...,484005199725384-LEAF_2-using-model-sem-lex.npy,"[0.48093784, -0.15828885, -0.20807397, 0.33676..."
10,8308362751140157,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,8308362751140157-GARLIC-using-model-sem-lex.npy,"[0.17171323, -0.28623503, -0.12528354, -0.0497..."
11,04184157795430421,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,04184157795430421-POP_2-using-model-sem-lex.npy,"[-0.024062917, -0.32942736, 0.23680398, 0.2938..."
12,13831097659377267,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,13831097659377267-WINDMILL_2-using-model-sem-l...,"[0.39966094, -0.18046072, -0.19201395, 0.46263..."
13,1291343204301616,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,1291343204301616-SMELL-using-model-sem-lex.npy,"[-0.050582692, -0.38552028, 0.0184002, 0.41410..."
14,15014149504236607,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,15014149504236607-REMEMBER-using-model-sem-lex...,"[0.02238021, -0.3168291, 0.091563605, 0.246568..."
15,13036467932378804,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,13036467932378804-EXPERT-using-model-sem-lex.npy,"[-0.3959899, 0.08070447, -0.2314913, 0.7215215..."
16,3615989994799924,/opt/home/cleong/data/ASL_Citizen/embeddings/3...,3615989994799924-EVERY_NIGHT-using-model-sem-l...,"[-0.06737868, -0.67983913, -0.2818894, -0.0925..."
17,9125117637454339,/opt/home/cleong/data/ASL_Citizen/embeddings/9...,9125117637454339-PEPSI-using-model-sem-lex.npy,"[0.123861626, 0.028071826, 0.009182431, 0.4138..."
18,032764070871353246,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,032764070871353246-CORN_3-using-model-sem-lex.npy,"[-0.26545796, -0.13846815, 0.085592866, 0.0215..."
19,7304560060145906,/opt/home/cleong/data/ASL_Citizen/embeddings/7...,7304560060145906-WHY_NOT-using-model-sem-lex.npy,"[0.24915117, -0.17173235, 0.051909924, -0.0476..."

In [113]:
def get_embeddings_array_from_df(df):
    embeddings_array = np.stack(df["embedding"].values)
    return embeddings_array

In [114]:
get_embeddings_array_from_df(query_df).shape

(20, 768)

In [115]:
ref_df = paths_to_dataframe(reference_paths)

loading paths: 100%|██████████| 83092/83092 [14:00<00:00, 98.86it/s]

In [120]:
recombined_df = pd.concat([query_df, ref_df], ignore_index=True)

https://www.pinecone.io/learn/series/faiss/faiss-tutorial/ shows how to do this with a pandas dataframe

In [121]:
signclip_embedding_d = 768
d = signclip_embedding_d                           # dimension

nb = len(reference_paths)                      # database size
nq = len(query_paths)                      # nb of queries
np.random.seed(1234)             # make reproducible
# xb = get_embeddings_array_from_df(ref_df)
xb = get_embeddings_array_from_df(recombined_df)
xq = get_embeddings_array_from_df(query_df)

xb.shape, xq.shape

((83112, 768), (20, 768))

In [122]:

index = faiss.IndexFlatIP(d)
index = faiss.index_cpu_to_gpu(res, 0, index)
print(index.is_trained)
faiss.normalize_L2(xb) # normalize
index.add(xb)                  # add vectors to the index
print(index.ntotal)

True
83112

In [126]:
# data['sentence_A'].iloc[[4586, 10252, 12465, 190]]
recombined_df.iloc[[0, 3]]

,video_id,file_path,file_name,embedding
0,4512868342911205,/opt/home/cleong/data/ASL_Citizen/embeddings/4...,4512868342911205-RESPONSIBILITY-using-model-se...,"[-0.33322427, 0.16524771, 0.11535681, 0.368136..."
3,1989909351732737,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,1989909351732737-FUNCTION-using-model-sem-lex.npy,"[-0.024617223, -0.20148936, -0.0022485945, 0.2..."

In [139]:
def search_and_output_indices(query_df, k=4):
    xq = get_embeddings_array_from_df(query_df)
    
    # xq = list_of_paths_to_np_array(query_paths)
    faiss.normalize_L2(xq) # normalize query vectors before search
    D, I = index.search(xq, k)     # Distances and Indexes of neighbors
    # print(I[:5])                   # neighbors of the 5 first queries
    print()
    for q_index, neighbors in enumerate(I):
        print(q_index)
        query_file = query_df['file_name'].iloc[q_index]

        # print(f"Query Path: {query_df['file_name'][q_index].name}")
        print(f"Query File: {query_file}")
        # print(query_file)
        for k_index, neighbor in enumerate(neighbors):
            
            
            distance_to_neighbor = D[q_index][k_index]
            db_index_of_neighbor = I[q_index][k_index]
            # print(f"{distance_to_neighbor} similarity")
            # print("Result File")
            result_file = recombined_df['file_name'].iloc[db_index_of_neighbor]
            print("*", distance_to_neighbor,result_file)
    # print(I[-5:])                  # neighbors of the 5 last queries
# search_and_output_original_paths(reference_paths[:5])
    return I


search_and_output_indices(recombined_df.head())

0
Query File: 4512868342911205-RESPONSIBILITY-using-model-sem-lex.npy
* 0.99999994 4512868342911205-RESPONSIBILITY-using-model-sem-lex.npy
* 0.94378984 05789382245740726-RESPONSIBILITY-using-model-sem-lex.npy
* 0.9384923 37172909077776795-RESPONSIBILITY-using-model-sem-lex.npy
* 0.9375743 10866847898271859-RESPONSIBILITY-using-model-sem-lex.npy
1
Query File: 802432162454322-VITAMINS-using-model-sem-lex.npy
* 1.0000001 802432162454322-VITAMINS-using-model-sem-lex.npy
* 0.97884727 36886063518419365-VANILLA-using-model-sem-lex.npy
* 0.95855355 1201537952691305-GOTCHA-using-model-sem-lex.npy
* 0.9569726 4150403650861141-VANILLA-using-model-sem-lex.npy
2
Query File: 29766213567797584-ENVELOPE-using-model-sem-lex.npy
* 0.99999994 29766213567797584-ENVELOPE-using-model-sem-lex.npy
* 0.8125504 8842998926765759-OFF-using-model-sem-lex.npy
* 0.80976224 5666794693555826-COOL_3-using-model-sem-lex.npy
* 0.80927503 5941139621427864-ENVELOPE-using-model-sem-lex.npy
3
Query File: 1989909351732737-FUNCTION-using-model-sem-lex.npy
* 0.9999998 1989909351732737-FUNCTION-using-model-sem-lex.npy
* 0.9403515 899035896070709-FUNCTION-using-model-sem-lex.npy
* 0.9385063 38434113923205127-PORCUPINE-using-model-sem-lex.npy
* 0.9338164 5716557271797269-9_OCLOCK-using-model-sem-lex.npy
4
Query File: 7075908041208987-STORY_3-using-model-sem-lex.npy
* 1.0000001 7075908041208987-STORY_3-using-model-sem-lex.npy
* 0.9559816 8516705447348785-COMMENT-using-model-sem-lex.npy
* 0.91182286 21023376509352976-COMMENT-using-model-sem-lex.npy
* 0.9100569 21293374032745094-STORY_3-using-model-sem-lex.npy

array([[    0, 76462,  2889,  4184],
       [    1,  2566,  5324, 26912],
       [    2, 35168, 19509, 72424],
       [    3, 61666, 51239, 26410],
       [    4, 47227, 54058, 19592]])

In [143]:
sail_df = recombined_df[recombined_df['file_name'].str.contains("SAIL_2", na=False)]
sail_df

,video_id,file_path,file_name,embedding
6,029833014387566248,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,029833014387566248-SAIL_2-using-model-sem-lex.npy,"[-0.20589952, -0.4929245, -0.405769, 0.4774660..."
52,25193493599062466,/opt/home/cleong/data/ASL_Citizen/embeddings/2...,25193493599062466-SAIL_2-using-model-sem-lex.npy,"[0.020708017, -0.64416075, -0.571725, 0.414683..."
1104,998664525579968,/opt/home/cleong/data/ASL_Citizen/embeddings/9...,998664525579968-SAIL_2-using-model-sem-lex.npy,"[-0.028152522, -0.17866078, -0.40053686, 0.612..."
3232,3561548719390817,/opt/home/cleong/data/ASL_Citizen/embeddings/3...,3561548719390817-SAIL_2-using-model-sem-lex.npy,"[-0.07449641, 0.14802885, -0.15747677, 0.63058..."
5293,271562403427132,/opt/home/cleong/data/ASL_Citizen/embeddings/2...,271562403427132-SAIL_2-using-model-sem-lex.npy,"[0.11556907, -0.47648573, -0.069870405, 0.0706..."
9224,6963257268664678,/opt/home/cleong/data/ASL_Citizen/embeddings/6...,6963257268664678-SAIL_2-using-model-sem-lex.npy,"[-0.15684293, -0.17237327, -0.2684914, 0.72625..."
9864,3037369286672158,/opt/home/cleong/data/ASL_Citizen/embeddings/3...,3037369286672158-SAIL_2-using-model-sem-lex.npy,"[0.14184958, -0.1991123, -0.38218364, 0.547064..."
13270,7450908595041557,/opt/home/cleong/data/ASL_Citizen/embeddings/7...,7450908595041557-SAIL_2-using-model-sem-lex.npy,"[-0.3905956, -0.17760131, -0.19289908, 0.68476..."
13358,577224478912544,/opt/home/cleong/data/ASL_Citizen/embeddings/5...,577224478912544-SAIL_2-using-model-sem-lex.npy,"[-0.13551623, 0.08971065, -0.31820688, 0.47439..."
14201,25978172118606313,/opt/home/cleong/data/ASL_Citizen/embeddings/2...,25978172118606313-SAIL_2-using-model-sem-lex.npy,"[0.03173498, 0.15703946, 0.034203187, 0.459587..."
14608,19910436412347976,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,19910436412347976-SAIL_2-using-model-sem-lex.npy,"[0.0049261414, -0.5257914, -0.20019308, 0.2236..."
15144,19158377715411268,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,19158377715411268-SAIL_2-using-model-sem-lex.npy,"[0.24416307, 0.0027248636, -0.3621003, 0.12870..."
16053,045654445738952054,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,045654445738952054-SAIL_2-using-model-sem-lex.npy,"[-0.209271, -0.005634311, 0.019117825, 0.64169..."
20835,8511226712327007,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,8511226712327007-SAIL_2-using-model-sem-lex.npy,"[0.31996566, -0.35016727, -0.3874429, 0.119781..."
26826,19884607898478812,/opt/home/cleong/data/ASL_Citizen/embeddings/1...,19884607898478812-SAIL_2-using-model-sem-lex.npy,"[-0.13370928, -0.16403525, -0.29609033, 0.3530..."
32199,0005105598398187361,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,0005105598398187361-SAIL_2-using-model-sem-lex...,"[-0.06427234, 0.0003406601, 0.08596133, 0.4763..."
37108,07263556568701013,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,07263556568701013-SAIL_2-using-model-sem-lex.npy,"[-0.14377183, -0.20624204, -0.2613016, 0.77935..."
38394,5526703075746617,/opt/home/cleong/data/ASL_Citizen/embeddings/5...,5526703075746617-SAIL_2-using-model-sem-lex.npy,"[0.17237782, -0.39666465, -0.41111287, 0.59750..."
39462,9631908145667796,/opt/home/cleong/data/ASL_Citizen/embeddings/9...,9631908145667796-SAIL_2-using-model-sem-lex.npy,"[-0.2744717, -0.08382349, -0.13855061, 0.52397..."
41717,5671220265034711,/opt/home/cleong/data/ASL_Citizen/embeddings/5...,5671220265034711-SAIL_2-using-model-sem-lex.npy,"[0.053361613, -0.2541913, -0.18040168, 0.34989..."
43514,8130669293274413,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,8130669293274413-SAIL_2-using-model-sem-lex.npy,"[0.24939986, -0.29102087, -0.18385388, 0.08921..."
47402,44612090113642533,/opt/home/cleong/data/ASL_Citizen/embeddings/4...,44612090113642533-SAIL_2-using-model-sem-lex.npy,"[-0.008020805, -0.11714136, -0.34545618, 0.481..."
48017,5501236782580607,/opt/home/cleong/data/ASL_Citizen/embeddings/5...,5501236782580607-SAIL_2-using-model-sem-lex.npy,"[-0.0017705839, -0.40033954, 0.0024303906, -0...."
54313,7719824665425994,/opt/home/cleong/data/ASL_Citizen/embeddings/7...,7719824665425994-SAIL_2-using-model-sem-lex.npy,"[0.22558215, -0.54814196, -0.11058937, 0.09071..."
54929,45335513641208536,/opt/home/cleong/data/ASL_Citizen/embeddings/4...,45335513641208536-SAIL_2-using-model-sem-lex.npy,"[-0.15469033, -0.18102165, -0.2784323, 0.72698..."
58683,4641293355849112,/opt/home/cleong/data/ASL_Citizen/embeddings/4...,4641293355849112-SAIL_2-using-model-sem-lex.npy,"[-0.20887803, -0.1384546, -0.040904097, 0.4051..."
61622,8365337464131144,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,8365337464131144-SAIL_2-using-model-sem-lex.npy,"[0.47835255, -0.17359662, -0.5777932, 0.188975..."
64767,8298420400860262,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,8298420400860262-SAIL_2-using-model-sem-lex.npy,"[-0.29641852, 0.10966784, -0.35401118, 0.63945..."
68106,8532015518358596,/opt/home/cleong/data/ASL_Citizen/embeddings/8...,8532015518358596-SAIL_2-using-model-sem-lex.npy,"[-0.36917588, -0.123870015, -0.13685465, 0.772..."
68874,5493974082836584,/opt/home/cleong/data/ASL_Citizen/embeddings/5...,5493974082836584-SAIL_2-using-model-sem-lex.npy,"[0.2311417, -0.08732566, -0.38357967, 0.152957..."
70953,0662192799664183,/opt/home/cleong/data/ASL_Citizen/embeddings/0...,0662192799664183-SAIL_2-using-model-sem-lex.npy,"[0.047974017, -0.040065378, -0.29093257, 0.870..."

In [144]:
search_and_output_indices(sail_df)

0
Query File: 029833014387566248-SAIL_2-using-model-sem-lex.npy
* 1.0 029833014387566248-SAIL_2-using-model-sem-lex.npy
* 0.9211222 7991265889046182-SAILBOAT-using-model-sem-lex.npy
* 0.91164017 19884607898478812-SAIL_2-using-model-sem-lex.npy
* 0.89361244 5526703075746617-SAIL_2-using-model-sem-lex.npy
1
Query File: 25193493599062466-SAIL_2-using-model-sem-lex.npy
* 1.0 25193493599062466-SAIL_2-using-model-sem-lex.npy
* 0.8849796 732802596992111-MORNING-using-model-sem-lex.npy
* 0.8836915 5791417290435064-ERUPT_1-using-model-sem-lex.npy
* 0.8728297 2115074159591035-SAILBOAT-using-model-sem-lex.npy
2
Query File: 998664525579968-SAIL_2-using-model-sem-lex.npy
* 1.0000001 998664525579968-SAIL_2-using-model-sem-lex.npy
* 0.91859174 43820531816223984-SAILBOAT-using-model-sem-lex.npy
* 0.9121847 10481713339451981-CAMCORDER-using-model-sem-lex.npy
* 0.9060828 501034080069992-SAILBOAT-using-model-sem-lex.npy
3
Query File: 3561548719390817-SAIL_2-using-model-sem-lex.npy
* 1.0000001 3561548719390817-SAIL_2-using-model-sem-lex.npy
* 0.92676276 43874327482898967-SAILBOAT-using-model-sem-lex.npy
* 0.9120406 0662192799664183-SAIL_2-using-model-sem-lex.npy
* 0.91057116 577224478912544-SAIL_2-using-model-sem-lex.npy
4
Query File: 271562403427132-SAIL_2-using-model-sem-lex.npy
* 1.0000001 271562403427132-SAIL_2-using-model-sem-lex.npy
* 0.96121794 5050869979436594-MINE-using-model-sem-lex.npy
* 0.91667724 30106716928511124-POPULAR-using-model-sem-lex.npy
* 0.91401964 750495647980892-CANDLE-using-model-sem-lex.npy
5
Query File: 6963257268664678-SAIL_2-using-model-sem-lex.npy
* 0.9999999 6963257268664678-SAIL_2-using-model-sem-lex.npy
* 0.9417281 2777659330539366-SAILBOAT-using-model-sem-lex.npy
* 0.9413981 0662192799664183-SAIL_2-using-model-sem-lex.npy
* 0.93952787 44612090113642533-SAIL_2-using-model-sem-lex.npy
6
Query File: 3037369286672158-SAIL_2-using-model-sem-lex.npy
* 1.0000002 3037369286672158-SAIL_2-using-model-sem-lex.npy
* 0.9216199 37133917405214634-FOREST-using-model-sem-lex.npy
* 0.91492915 5001668636132224-FOREST-using-model-sem-lex.npy
* 0.89475155 2124320580569654-FOREST-using-model-sem-lex.npy
7
Query File: 7450908595041557-SAIL_2-using-model-sem-lex.npy
* 1.0000001 7450908595041557-SAIL_2-using-model-sem-lex.npy
* 0.96976566 45335513641208536-SAIL_2-using-model-sem-lex.npy
* 0.95188236 7349301060722773-SAILBOAT-using-model-sem-lex.npy
* 0.93046904 8298420400860262-SAIL_2-using-model-sem-lex.npy
8
Query File: 577224478912544-SAIL_2-using-model-sem-lex.npy
* 1.0000001 577224478912544-SAIL_2-using-model-sem-lex.npy
* 0.9603133 44612090113642533-SAIL_2-using-model-sem-lex.npy
* 0.9475316 45335513641208536-SAIL_2-using-model-sem-lex.npy
* 0.94495153 43874327482898967-SAILBOAT-using-model-sem-lex.npy
9
Query File: 25978172118606313-SAIL_2-using-model-sem-lex.npy
* 1.0 25978172118606313-SAIL_2-using-model-sem-lex.npy
* 0.9381611 7833771029581036-SAILBOAT-using-model-sem-lex.npy
* 0.9200769 8759129523620577-PROPOSE-using-model-sem-lex.npy
* 0.91630447 8888945699898234-LIST-using-model-sem-lex.npy
10
Query File: 19910436412347976-SAIL_2-using-model-sem-lex.npy
* 1.0000002 19910436412347976-SAIL_2-using-model-sem-lex.npy
* 0.92043304 38589512774835044-TICKET-using-model-sem-lex.npy
* 0.9026836 9514308349626412-MINE-using-model-sem-lex.npy
* 0.9003235 24913890528376736-TOAST-using-model-sem-lex.npy
11
Query File: 19158377715411268-SAIL_2-using-model-sem-lex.npy
* 1.0 19158377715411268-SAIL_2-using-model-sem-lex.npy
* 0.8612116 22974156777864607-SAILBOAT-using-model-sem-lex.npy
* 0.8597847 484530019936086-MAJOR-using-model-sem-lex.npy
* 0.8575115 9004554816227568-KITE-using-model-sem-lex.npy
12
Query File: 045654445738952054-SAIL_2-using-model-sem-lex.npy
* 1.0 045654445738952054-SAIL_2-using-model-sem-lex.npy
* 0.906459 6490746969629444-CANDLE-using-model-sem-lex.npy
* 0.89760685 8758073493981038-CANDLE-using-model-sem-lex.npy
* 0.8953597 5946508818663139-BOIL_2-using-model-sem-lex.npy
13
Query File: 8511226712327007-SAIL_2-using-model-sem-lex.npy
* 0.99999994 8511226712327007-SAIL_2-using-model-sem-lex.npy
* 0.9078171 170703539732588-CANDLE-using-model-sem-lex.npy
* 0.9015732 1418971680172565-KITE-using-model-sem-lex.npy
* 0.89987314 271562403427132-SAIL_2-using-model-sem-lex.npy
14
Query File: 19884607898478812-SAIL_2-using-model-sem-lex.npy
* 1.0000001 19884607898478812-SAIL_2-using-model-sem-lex.npy
* 0.9226346 7991265889046182-SAILBOAT-using-model-sem-lex.npy
* 0.9177216 5143489040370806-SAILBOAT-using-model-sem-lex.npy
* 0.9165418 9631908145667796-SAIL_2-using-model-sem-lex.npy
15
Query File: 0005105598398187361-SAIL_2-using-model-sem-lex.npy
* 0.99999976 0005105598398187361-SAIL_2-using-model-sem-lex.npy
* 0.88012165 7128610817949148-PIRATE-using-model-sem-lex.npy
* 0.87596047 25978172118606313-SAIL_2-using-model-sem-lex.npy
* 0.87118995 7682846879252789-WILL_GO-using-model-sem-lex.npy
16
Query File: 07263556568701013-SAIL_2-using-model-sem-lex.npy
* 0.9999997 07263556568701013-SAIL_2-using-model-sem-lex.npy
* 0.96619135 6310649492382339-SAILBOAT-using-model-sem-lex.npy
* 0.9350152 15013912476924496-MORNING-using-model-sem-lex.npy
* 0.9334606 5303999633655436-LIGHT_CANDLE-using-model-sem-lex.npy
17
Query File: 5526703075746617-SAIL_2-using-model-sem-lex.npy
* 0.99999994 5526703075746617-SAIL_2-using-model-sem-lex.npy
* 0.89361244 029833014387566248-SAIL_2-using-model-sem-lex.npy
* 0.8917636 43820531816223984-SAILBOAT-using-model-sem-lex.npy
* 0.8888526 9218428614587915-ENVIRONMENT-using-model-sem-lex.npy
18
Query File: 9631908145667796-SAIL_2-using-model-sem-lex.npy
* 0.9999996 9631908145667796-SAIL_2-using-model-sem-lex.npy
* 0.9686347 4641293355849112-SAIL_2-using-model-sem-lex.npy
* 0.9491033 25122212352325946-SAILBOAT-using-model-sem-lex.npy
* 0.93003035 7991265889046182-SAILBOAT-using-model-sem-lex.npy
19
Query File: 5671220265034711-SAIL_2-using-model-sem-lex.npy
* 0.9999998 5671220265034711-SAIL_2-using-model-sem-lex.npy
* 0.935177 29671918431445565-SAILBOAT-using-model-sem-lex.npy
* 0.88708806 6490746969629444-CANDLE-using-model-sem-lex.npy
* 0.886561 7991265889046182-SAILBOAT-using-model-sem-lex.npy
20
Query File: 8130669293274413-SAIL_2-using-model-sem-lex.npy
* 1.0000002 8130669293274413-SAIL_2-using-model-sem-lex.npy
* 0.8683698 1090904597386797-LABEL-using-model-sem-lex.npy
* 0.86619747 938255370696083-DEMAND-using-model-sem-lex.npy
* 0.86611104 06898797735512252-SCREWDRIVER-using-model-sem-lex.npy
21
Query File: 44612090113642533-SAIL_2-using-model-sem-lex.npy
* 1.0000001 44612090113642533-SAIL_2-using-model-sem-lex.npy
* 0.9603133 577224478912544-SAIL_2-using-model-sem-lex.npy
* 0.95058846 43874327482898967-SAILBOAT-using-model-sem-lex.npy
* 0.9440947 0662192799664183-SAIL_2-using-model-sem-lex.npy
22
Query File: 5501236782580607-SAIL_2-using-model-sem-lex.npy
* 1.0000002 5501236782580607-SAIL_2-using-model-sem-lex.npy
* 0.8646712 271562403427132-SAIL_2-using-model-sem-lex.npy
* 0.8640096 04074282397715301-DISTRACTED-using-model-sem-lex.npy
* 0.8586156 5050869979436594-MINE-using-model-sem-lex.npy
23
Query File: 7719824665425994-SAIL_2-using-model-sem-lex.npy
* 0.99999964 7719824665425994-SAIL_2-using-model-sem-lex.npy
* 0.89241755 07675913965684344-SAILBOAT-using-model-sem-lex.npy
* 0.84658384 31159133349433676-WIN-using-model-sem-lex.npy
* 0.8458104 7496447065789817-HOTEL-using-model-sem-lex.npy
24
Query File: 45335513641208536-SAIL_2-using-model-sem-lex.npy
* 0.9999998 45335513641208536-SAIL_2-using-model-sem-lex.npy
* 0.9723709 7349301060722773-SAILBOAT-using-model-sem-lex.npy
* 0.96976566 7450908595041557-SAIL_2-using-model-sem-lex.npy
* 0.9539872 43874327482898967-SAILBOAT-using-model-sem-lex.npy
25
Query File: 4641293355849112-SAIL_2-using-model-sem-lex.npy
* 1.0000002 4641293355849112-SAIL_2-using-model-sem-lex.npy
* 0.9686347 9631908145667796-SAIL_2-using-model-sem-lex.npy
* 0.9457102 25122212352325946-SAILBOAT-using-model-sem-lex.npy
* 0.9113473 7991265889046182-SAILBOAT-using-model-sem-lex.npy
26
Query File: 8365337464131144-SAIL_2-using-model-sem-lex.npy
* 1.0 8365337464131144-SAIL_2-using-model-sem-lex.npy
* 0.8520648 2637761750000225-PLENTY-using-model-sem-lex.npy
* 0.8492626 26118850844508756-SINK-using-model-sem-lex.npy
* 0.84799445 6756254551437855-CULTURE-using-model-sem-lex.npy
27
Query File: 8298420400860262-SAIL_2-using-model-sem-lex.npy
* 0.9999999 8298420400860262-SAIL_2-using-model-sem-lex.npy
* 0.9444778 11852342349625133-SAIL-using-model-sem-lex.npy
* 0.9411391 43874327482898967-SAILBOAT-using-model-sem-lex.npy
* 0.9390863 44612090113642533-SAIL_2-using-model-sem-lex.npy
28
Query File: 8532015518358596-SAIL_2-using-model-sem-lex.npy
* 1.0000002 8532015518358596-SAIL_2-using-model-sem-lex.npy
* 0.8807899 09635620025138936-MORNING-using-model-sem-lex.npy
* 0.8789836 7349301060722773-SAILBOAT-using-model-sem-lex.npy
* 0.86809206 45335513641208536-SAIL_2-using-model-sem-lex.npy
29
Query File: 5493974082836584-SAIL_2-using-model-sem-lex.npy
* 0.99999994 5493974082836584-SAIL_2-using-model-sem-lex.npy
* 0.89129275 22974156777864607-SAILBOAT-using-model-sem-lex.npy
* 0.89084744 43035172124371845-KITE-using-model-sem-lex.npy
* 0.8785583 6555415177977078-MINE-using-model-sem-lex.npy
30
Query File: 0662192799664183-SAIL_2-using-model-sem-lex.npy
* 1.0 0662192799664183-SAIL_2-using-model-sem-lex.npy
* 0.9647942 3379109157521345-SAIL-using-model-sem-lex.npy
* 0.9508023 9030811960489882-SAILBOAT-using-model-sem-lex.npy
* 0.9440947 44612090113642533-SAIL_2-using-model-sem-lex.npy

array([[    6, 73882, 26826, 38394],
       [   52, 75575, 19559, 43675],
       [ 1104, 21763, 53395, 52713],
       [ 3232,  7065, 70953, 13358],
       [ 5293,  9693, 59365, 76958],
       [ 9224, 64801, 70953, 47402],
       [ 9864, 61945, 28003, 19493],
       [13270, 54929, 74346, 64767],
       [13358, 47402, 54929,  7065],
       [14201, 57969, 27621, 31570],
       [14608, 52124, 67136, 31766],
       [15144, 70053, 51773, 43111],
       [16053, 60564, 73760, 73567],
       [20835, 22632,  7759,  5293],
       [26826, 73882,  1668, 39462],
       [32199, 59741, 14201, 74413],
       [37108, 33162, 61525, 29194],
       [38394,     6, 21763, 39590],
       [39462, 58683, 38106, 73882],
       [41717, 29181, 60564, 73882],
       [43514, 15150, 21726, 19511],
       [47402, 13358,  7065, 70953],
       [48017,  5293, 50653,  9693],
       [54313, 11970, 52870, 72253],
       [54929, 74346, 13270,  7065],
       [58683, 39462, 38106, 73882],
       [61622, 48178, 41061, 57033],
       [64767, 41317,  7065, 47402],
       [68106, 50339, 74346, 54929],
       [68874, 70053, 21364, 66064],
       [70953, 49109, 75079, 47402]])

PCA and Clustering
https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization

In [154]:
def do_pca(mt, d=768, d_out=10):
    # random training data 
    # mt = np.random.rand(1000, d).astype('float32')
    mat = faiss.PCAMatrix (d, d_out)
    mat.train(mt)
    assert mat.is_trained
    tr = mat.apply(mt)
    return tr
    # print this to show that the magnitude of tr's columns is decreasing
    # print (tr ** 2).sum(0)
pca = do_pca(get_embeddings_array_from_df(recombined_df))
# print(tr.sum())

In [156]:
pca.shape

(83112, 10)